const os = require('node:os')

console.log('Sistema operativo:')
console.log('Nombre: ', os.type())
console.log('Plataforma: ', os.platform())
console.log('Arquitectura: ', os.arch())
console.log('Versión: ', os.release())
console.log('Hostname: ', os.hostname())
console.log('Directorio de trabajo: ', os.homedir())
console.log('Memoria total: ', os.totalmem())
console.log('Memoria libre: ', os.freemem())
console.log('CPU: ', os.cpus())
console.log('Red: ', os.networkInterfaces())
console.log('Carga del sistema: ', os.loadavg())
console.log('Tiempo de actividad: ', os.uptime())
